//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCommon {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreCommon.ErrorCode", typeof(ErrorCode).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700008.
        /// </summary>
        public static string CreateInstanceConfigError {
            get {
                return ResourceManager.GetString("CreateInstanceConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700007.
        /// </summary>
        public static string CreateInstanceError {
            get {
                return ResourceManager.GetString("CreateInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700044.
        /// </summary>
        public static string CreateRepeatInstance {
            get {
                return ResourceManager.GetString("CreateRepeatInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700006.
        /// </summary>
        public static string GetAssemblyMethodConfigError {
            get {
                return ResourceManager.GetString("GetAssemblyMethodConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700005.
        /// </summary>
        public static string GetAssemblyMethodError {
            get {
                return ResourceManager.GetString("GetAssemblyMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700004.
        /// </summary>
        public static string GetAssemblyTypeConfigError {
            get {
                return ResourceManager.GetString("GetAssemblyTypeConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700003.
        /// </summary>
        public static string GetAssemblyTypeError {
            get {
                return ResourceManager.GetString("GetAssemblyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700012.
        /// </summary>
        public static string InvalidServiceCode {
            get {
                return ResourceManager.GetString("InvalidServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700009.
        /// </summary>
        public static string InvokeMethodError {
            get {
                return ResourceManager.GetString("InvokeMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700002.
        /// </summary>
        public static string LoadAssemblyConfigError {
            get {
                return ResourceManager.GetString("LoadAssemblyConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700001.
        /// </summary>
        public static string LoadAssemblyError {
            get {
                return ResourceManager.GetString("LoadAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700011.
        /// </summary>
        public static string LoadServicesParameterError {
            get {
                return ResourceManager.GetString("LoadServicesParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700043.
        /// </summary>
        public static string ReadCommentError {
            get {
                return ResourceManager.GetString("ReadCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000003.
        /// </summary>
        public static string RemoeError {
            get {
                return ResourceManager.GetString("RemoeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000002.
        /// </summary>
        public static string UnexpectError {
            get {
                return ResourceManager.GetString("UnexpectError", resourceCulture);
            }
        }
    }
}
